import { Document, Page, Text, View, StyleSheet} from '@react-pdf/renderer';
import type { ReportType } from '../../types/financial';
import { formatCurrency } from '../../utils/format';

// Create styles
const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 12 },
  header: { marginBottom: 20, borderBottom: 1, paddingBottom: 10 },
  title: { fontSize: 24, fontWeight: 'bold' },
  section: { marginVertical: 10 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 },
  label: { color: '#666' },
  value: { fontWeight: 'bold' },
  footer: { marginTop: 50, textAlign: 'center', color: '#999', fontSize: 10 }
});

export const ReportPDF = ({ report }: { report: ReportType }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Financial Report</Text>
        <Text style={styles.label}>Period: {report.period}</Text>
      </View>

      <View style={styles.section}>
        <View style={styles.row}>
          <Text style={styles.label}>Total Income:</Text>
          <Text style={styles.value}>{formatCurrency(report.totalIncome)}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Total Expenses:</Text>
          <Text style={styles.value}>{formatCurrency(report.totalExpenses)}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Net Savings:</Text>
          <Text style={styles.value}>{formatCurrency(report.totalIncome - report.totalExpenses)}</Text>
        </View>
      </View>

      <Text style={styles.footer}>Generated by Your Finance App on {new Date().toLocaleDateString()}</Text>
    </Page>
  </Document>
);